Device Switch! (The Tank v2!) - SMD Updated to v7!   - Removed Rotate module   - Added Display Module   - Added native SwayIPC communicator   - Security Fixes     - File and Permission checks!   - Updated the Locker module to work with Sway   - Updated the Dispatcher     - Now can monitor Tasks and trigger them directly     - Async Process monitor with optional function execution   - Backups can now be queued   - Backups now do the compress|encrypt in one step!     - Tar is piped into Openssl   - Backups can run commands before and after     - After commands still work on fail     - Pre commands can stop the Backup     - Can be used to automount and unmount a device   - Backup Plans can now have seperate dirs and upload targets   - Broke out constants and utils     - Defaults are their own file now   - Fixed loader not working when dynamic directory is overritten   - Updated the way we do logging     - Removed redundent time and name when doing journald logging   - Python formatting   - Updated some module functions into a non-changing "lib.shared" directory   - Moved USB resolving into the server-side for Hydra   - Reduced needed thread count   - Hydra device updates     - Added the ability to add efi/pflash/flash/usb drive types     - bios file, intirid and kernel support     - Support for OSK for MacOS VMs     - Fixes for TPM support   - Better QMP and QEMUGA command handeling   - Removed noVNC and Nginx support from Hydra   - Better handeling of Lid detection   - Better screen handeling     - Allows for auto-detection and activation of new screens!   - Added Bluetooth and Wireless radio change event triggers!   - Faster handeling of requests of attributes with Flex for Message   - Reduced the pack/unpack size of Messages   - Added a payload limit 2^32-1 on Messages - Many Config Changes and Updates   - Network Manager   - Bluetooth     - Fixed audio through WirePlumber     - Bluetooth Microphones work now!   - Chromium Policy   - WirePlumber works way better now - Switch from X11 to Wayland (Sway) - Switch from IPTables to NFTables - Added faillock with proper config - Updated taglines and copyright with new year changes   - We've been at this for ~8 years! - Added MoonlightSky theme!

diff --git a/usr/lib/smd/sbin/smb b/usr/lib/smd/sbin/smb
--- a/usr/lib/smd/sbin/smb
+++ b/usr/lib/smd/sbin/smb
@@ -1,9 +1,25 @@
 #!/usr/bin/dash
-# SMB Connect Sudo Wrapper
+################################
+### iDigitalFlame  2016-2024 ###
+#                              #
+#            -/`               #
+#            -yy-   :/`        #
+#         ./-shho`:so`         #
+#    .:- /syhhhh//hhs` `-`     #
+#   :ys-:shhhhhhshhhh.:o- `    #
+#   /yhsoshhhhhhhhhhhyho`:/.   #
+#   `:yhyshhhhhhhhhhhhhh+hd:   #
+#     :yssyhhhhhyhhhhhhhhdd:   #
+#    .:.oyshhhyyyhhhhhhddd:    #
+#    :o+hhhhhyssyhhdddmmd-     #
+#     .+yhhhhyssshdmmddo.      #
+#       `///yyysshd++`         #
+#                              #
+########## SPACEPORT ###########
+### Spaceport + SMD
+## Samba Mount Sudo Wrapper
 #
-# System Management Daemon
-#
-# Copyright (C) 2016 - 2023 iDigitalFlame
+# Copyright (C) 2016 - 2024 iDigitalFlame
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -24,13 +40,13 @@ if ! [ "$USER" = "root" ]; then
     exit 1
 fi
 if [ $# -ne 2 ]; then
-    echo "Invalid arguments!"
+    printf "%s <mount> <path>\n" "$0"
     exit 1
 fi
 
 input=$(cat -)
 if [ -z "$input" ]; then
-    echo "Invalid input!"
+    echo "No input was provided!"
     exit 1
 fi
 
@@ -38,11 +54,15 @@ user=$(echo "$input" | awk -F'\b' '{print $1}')
 domain=$(echo "$input" | awk -F'\b' '{print $2}')
 password=$(echo "$input" | awk -F'\b' '{print $3}')
 username=$(echo "$input" | awk -F'\b' '{print $4}')
+
+input=""
+unset input
+
 if [ -z "$user" ] || [ -z "$password" ] || [ -z "$username" ]; then
-    echo "Invalid input!"
+    echo "Inpu was invalid!"
     exit 1
 fi
-if [ ! -d "$2" ]; then
+if ! [ -d "$2" ]; then
     printf "Mount path \"%s\" does not exist or is not a directory!\n" "$2"
     exit 1
 fi
@@ -53,9 +73,14 @@ result=$?
 
 export PASSWD=""
 unset PASSWD
+
 user=""
 domain=""
 password=""
 username=""
+unset user
+unset domain
+unset password
+unset username
 
 exit $result
