Updated Profiles and re-ordered some lines

diff --git a/bin/relink b/bin/relink
--- a/bin/relink
+++ b/bin/relink
@@ -50,7 +50,7 @@ list() {
     list_target=${1%/}
     find "$list_target" -type f -not -wholename "$list_target"/.git/\* -print | while IFS= read -r list_file; do
         list_name=$(printf "%s" "$list_file" | awk "{gsub(\"${list_target}\", \"\"); print \$0}")
-        if ! echo "$list_name" | grep -qE '.(nlk|nolink)$|^/.git(|ignore$|config$|hub$)|^/(LICENSE|license|.vscode)$|^/[a-zA-Z0-9_.-]+.(md|vscode|MD|code-workspace)$'; then
+        if ! echo "$list_name" | grep -qE '.(nlk|nolink)$|^/.git(|ignore$|config$|hub$)|^/(LICENSE|license|.vscode)$|^/[a-zA-Z0-9_.-]+.(md|save|vscode|MD|code-workspace)$'; then
             check "${list_src}${list_name}" "${list_target}${list_name}"
         fi
     done
@@ -145,11 +145,11 @@ fi
 
 if [ $DRY -eq 0 ]; then
     if ! [ -d "$1" ]; then
-        printf 'Error: source directory "%s" does not exist!' "$1"
+        printf 'Error: source directory "%s" does not exist!\n' "$1"
     fi
     if ! [ -d "$2" ]; then
         if ! mkdir -p "$2" 2> /dev/null; then
-            printf 'Error: cannot create target directory "%s"!' "$2"
+            printf 'Error: cannot create target directory "%s"!\n' "$2"
             exit 1
         fi
     fi
