Linted scripts and Updated scripts to their respective versions

diff --git a/bin/relink b/bin/relink
--- a/bin/relink
+++ b/bin/relink
@@ -34,12 +34,12 @@ list() {
     if [ $# -ne 2 ]; then
         return 1
     fi
-    fc=${1%/}
-    ft=${2%/}
-    for file in $(find "$fc" -type f -print); do
-        fp=$(printf "$file" | awk "{gsub(\"${fc}\", \"\"); print \$1}")
-        if ! [ -z $(echo $fp | grep -vE '.(nlk|nolink)$|^/.git(|ignore$|config$)|^/(LICENSE|license|.vscode)$|^/[a-zA-Z0-9_.-]+.(md|vscode|MD|code-workspace)$') ]; then
-            check "$ft$fp" "$fc$fp"
+    files_src=${2%/}
+    files_target=${1%/}
+    find "$files_target" -type f -print | while IFS= read -r file; do
+        file_name=$(printf "%s" "$file" | awk "{gsub(\"${files_target}\", \"\"); print \$1}")
+        if ! echo "$file_name" | grep -qE '.(nlk|nolink)$|^/.git(|ignore$|config$)|^/(LICENSE|license|.vscode)$|^/[a-zA-Z0-9_.-]+.(md|vscode|MD|code-workspace)$'; then
+            check "${files_src}${file_name}" "${files_target}${file_name}"
         fi
     done
     return 0
@@ -50,24 +50,22 @@ link() {
         return 1
     fi
     rm -f "$1" 2> /dev/null
-    fd=$(dirname "$1")
-    if ! [ -d "$fd" ]; then
-        echo "Making \"$fd\".."
-        mkdir -p "$fd" 2> /dev/null
-        if [ $? -ne 0 ]; then
-            panic "Cannot create directory \"$fd\"!"
+    file_dir=$(dirname "$1")
+    if ! [ -d "$file_dir" ]; then
+        printf "Making \"%s\"..\n" "$file_dir"
+        if ! mkdir -p "$file_dir" 2> /dev/null; then
+            panic "Cannot create directory \"${file_dir}\"!"
         fi
         if [ "$USER" = "root" ]; then
-            chmod 555 "$fd"
+            chmod 0555 "$file_dir"
         else
-            chmod 755 "$fd"
+            chmod 0755 "$file_dir"
         fi
     fi
-    ln -s "$2" "$1"
-    if [ $? -ne 0 ]; then
-        panic "Could not link \"$1\" to \"$2\"!"
+    if ! ln -s "$2" "$1"; then
+        panic "Could not link \"${1}\" to \"${2}\"!"
     fi
-    echo "[+] Relinked \"$1\" to \"$2\"."
+    printf "[+] Relinked \"%s\" to \"%s\".\n" "$1" "$2"
     return 0
 }
 
@@ -76,19 +74,18 @@ check() {
         return 1
     fi
     if [ $DEBUG -eq 1 ]; then
-        echo "[+] Checking \"$1\".."
+        printf "[+] Checking \"%s\"..\n" "$1"
     fi
     if ! [ -L "$1" ]; then
-        echo "File \"$1\" is invalid, updating!"
+        printf "File \"%s\" is invalid, updating!\n" "$1"
         link "$1" "$2"
     else
-        fl=$(ls -al "$1" | awk '{print $11}')
-        if ! [ "$fl" = "$2" ]; then
-            echo "File \"$1\" is invalid, updating!"
+        if ! [ "$(readlink "$1")" = "$2" ]; then
+            printf "File \"%s\" is invalid, updating!\n" "$1"
             link "$1" "$2"
         else
             if [ $DEBUG -eq 1 ]; then
-                echo "File \"$1\" is valid!"
+                printf "File \"%s\" is valid!\n" "$1"
             fi
         fi
     fi
@@ -101,13 +98,11 @@ panic() {
 }
 
 if ! [ -d "$1" ]; then
-    panic "Config source \"$1\" does not exist!"
+    panic "Config source directory \"${1}\" does not exist!"
 fi
-
 if ! [ -d "$2" ]; then
-    mkdir -p "$2"
-    if [ $? -ne 0 ]; then
-        panic "Could not create target directory \"$2\"!"
+    if ! mkdir -p "$2" 2> /dev/null; then
+        panic "Could not create target directory \"${2}\"!"
     fi
 fi
 
